var wgmm = wgmm || {};

wgmm.data = {
  tables: [
    { id: 'table-1', name: 'Table #1' },
    { id: 'table-2', name: 'Table #2' },
    { id: 'table-3', name: 'Table #3' },
    { id: 'table-4', name: 'Table #4' },
    { id: 'table-5', name: 'Table #5' },
    { id: 'table-6', name: 'Table #6' },
    { id: 'table-7', name: 'Table #7' },
    { id: 'table-8', name: 'Table #8' },
    { id: 'table-9', name: 'Table #9' },
    { id: 'table-10', name: 'Table #10' },
    { id: 'table-11', name: 'Table #11' },
    { id: 'table-12', name: 'Table #12' }
  ],
  menuItems: [
    { id: 'item-1', name: 'raw juice', price: 3.95, category: 'fresh juices' },
    { id: 'item-2', name: 'fruit juice', price: 3.95, category: 'fresh juices' },
    { id: 'item-3', name: 'orange juice', price: 4.75, category: 'fresh juices' },
    { id: 'item-4', name: 'carrot juice ', price: 3.45, category: 'fresh juices' },
    { id: 'item-5', name: 'apple and orange juice ', price: 3.95, category: 'fresh juices' },
    { id: 'item-701', name: 'wagamama water, still (33cl)', price: 1.95, category: 'soft drinks' },
    { id: 'item-702', name: 'wagamama water, sparkling (33cl)', price: 1.95, category: 'soft drinks' },
    { id: 'item-703', name: 'wagamama water, still (75cl)', price: 3.95, category: 'soft drinks' },
    { id: 'item-704', name: 'wagamama water, sparkling (75cl)', price: 3.95, category: 'soft drinks' },
    { id: 'item-707', name: 'coca cola ', price: 2.15, category: 'soft drinks' },
    { id: 'item-708', name: 'coca cola light ', price: 2.15, category: 'soft drinks' },
    { id: 'item-709', name: 'lipton ice tea ', price: 2.45, category: 'soft drinks' },
    { id: 'item-711', name: 'sprite ', price: 2.15, category: 'soft drinks' },
    { id: 'item-712', name: 'fanta orange ', price: 2.15, category: 'soft drinks' },
    { id: 'item-713', name: 'canada dry ', price: 2.45, category: 'soft drinks' },
    { id: 'item-714', name: 'gini ', price: 2.45, category: 'soft drinks' },
    { id: 'item-601', name: 'de koninck ‘bolleke’', price: 2.3, category: 'beer' },
    { id: 'item-602', name: 'maes pils', price: 2.3, category: 'beer' },
    { id: 'item-605', name: 'kirin ichiban ', price: 3.95, category: 'beer' },
    { id: 'item-606', name: 'asahi super dry', price: 3.95, category: 'beer' },
    { id: 'item-607', name: 'iki beer ', price: 3.95, category: 'beer' },
    { id: 'item-401', name: 'wagamama house white wine (glass)', price: 3.45, category: 'wines' },
    { id: 'item-402', name: 'wagamama house white wine (50cl)', price: 9.75, category: 'wines' },
    { id: 'item-403', name: 'wagamama house white wine (bottle)', price: 13.45, category: 'wines' },
    { id: 'item-405', name: 'chardonnay (glass)', price: 3.95, category: 'wines' },
    { id: 'item-406', name: 'chardonnay (50cl)', price: 11.45, category: 'wines' },
    { id: 'item-407', name: 'chardonnay (bottle)', price: 15.95, category: 'wines' },
    { id: 'item-411', name: 'wagamama house red wine (glass)', price: 3.45, category: 'wines' },
    { id: 'item-412', name: 'wagamama house red wine (50cl)', price: 9.75, category: 'wines' },
    { id: 'item-413', name: 'wagamama house red wine (bottle)', price: 13.45, category: 'wines' },
    { id: 'item-415', name: 'merlot (glass)', price: 3.95, category: 'wines' },
    { id: 'item-416', name: 'merlot (50cl)', price: 11.45, category: 'wines' },
    { id: 'item-417', name: 'merlot (bottle)', price: 15.95, category: 'wines' },
    { id: 'item-421', name: 'wagamama house rosé wine (glass)', price: 3.45, category: 'wines' },
    { id: 'item-422', name: 'wagamama house rosé wine (50cl)', price: 9.75, category: 'wines' },
    { id: 'item-423', name: 'wagamama house rosé wine (bottle)', price: 13.45, category: 'wines' },
    { id: 'item-501', name: 'ozeki karakuchi ', price: 4.95, category: 'hot sake' },
    { id: 'item-801', name: 'coffee', price: 2.15, category: 'coffee' },
    { id: 'item-802', name: 'espresso', price: 2.15, category: 'coffee' },
    { id: 'item-803', name: 'cappucino', price: 2.45, category: 'coffee' },
    { id: 'item-804', name: 'caffè latte', price: 2.45, category: 'coffee' },
    { id: 'item-805', name: 'deca', price: 2.25, category: 'coffee' },
    { id: 'item-99', name: 'duck gyoza', price: 5.95, category: 'side dishes' },
    { id: 'item-100', name: 'gyoza', price: 5.95, category: 'side dishes' },
    { id: 'item-101', name: 'yasai gyoza ', price: 5.45, category: 'side dishes' },
    { id: 'item-102', name: 'ebi gyoza', price: 5.95, category: 'side dishes' },
    { id: 'item-103', name: 'ebi katsu', price: 5.95, category: 'side dishes' },
    { id: 'item-104', name: 'edamame', price: 4.6, category: 'side dishes' },
    { id: 'item-105', name: 'negima yakitori', price: 5.95, category: 'side dishes' },
    { id: 'item-106', name: 'grilled asparagus', price: 5.95, category: 'side dishes' },
    { id: 'item-108', name: 'tori kara age ', price: 5.95, category: 'side dishes' },
    { id: 'item-109', name: 'raw salad', price: 3.95, category: 'side dishes' },
    { id: 'item-110', name: 'miso soup and pickles', price: 2.45, category: 'side dishes' },
    { id: 'item-20', name: 'chicken ramen', price: 11.45, category: 'ramen ' },
    { id: 'item-21', name: 'wagamama seafood ramen', price: 13.95, category: 'ramen ' },
    { id: 'item-24', name: 'chilli beef ramen', price: 15.45, category: 'ramen ' },
    { id: 'item-25', name: 'chilli chicken ramen', price: 13.85, category: 'ramen ' },
    { id: 'item-27', name: 'moyashi soba', price: 10.5, category: 'ramen ' },
    { id: 'item-70', name: 'teriyaki chicken donburi', price: 13.5, category: 'donburi' },
    { id: 'item-35', name: 'ebi kare lomen', price: 12.95, category: 'kare noodle' },
    { id: 'item-36', name: 'chicken kare lomen', price: 12.45, category: 'kare noodle' },
    { id: 'item-37', name: 'chicken itame', price: 13.5, category: 'kare noodle' },
    { id: 'item-38', name: 'asai itame ', price: 11.5, category: 'kare noodle' },
    { id: 'item-39', name: 'duck niiro kare', price: 15.45, category: 'kare noodle' },
    { id: 'item-69', name: 'zasai beef gohan', price: 14.45, category: 'rice dishes' },
    { id: 'item-71', name: 'chicken katsu curry', price: 14.45, category: 'rice dishes' },
    { id: 'item-72', name: 'yasai katsu curry', price: 12.5, category: 'rice dishes' },
    { id: 'item-76', name: 'chicken tama rice', price: 12.5, category: 'rice dishes' },
    { id: 'item-77', name: 'cha han ', price: 12.95, category: 'rice dishes' },
    { id: 'item-78', name: 'yasai cha han ', price: 11.95, category: 'rice dishes' },
    { id: 'item-40', name: 'yaki soba', price: 12.85, category: 'teppan' },
    { id: 'item-41', name: 'yasai yaki soba', price: 10.5, category: 'teppan' },
    { id: 'item-42', name: 'yaki udon', price: 13.5, category: 'teppan' },
    { id: 'item-44', name: 'teriyaki steak soba', price: 15.45, category: 'teppan' },
    { id: 'item-45', name: 'teriyaki salmon soba  ', price: 15.45, category: 'teppan' },
    { id: 'item-125', name: 'steak salad', price: 12.95, category: 'salad' },
    { id: 'item-301', name: 'japanese rice', price: 2.45, category: 'extras' },
    { id: 'item-302', name: 'soba noodles ', price: 2.55, category: 'extras' },
    { id: 'item-304', name: 'chilli peppers ', price: 1.45, category: 'extras' },
    { id: 'item-308', name: 'wholewheat noodles', price: 2.55, category: 'extras' },
    { id: 'item-309', name: 'udon noodles ', price: 2.95, category: 'extras' },
    { id: 'item-310', name: '4 prawns ', price: 2.95, category: 'extras' },
    { id: 'item-313', name: 'curry sauce', price: 2.45, category: 'extras' },
    { id: 'item-314', name: '4 pieces of deep-fried tofu', price: 2.45, category: 'extras' },
    { id: 'item-49', name: 'chicken chilli men', price: 13.95, category: 'chilli men' },
    { id: 'item-50', name: 'ebi chilli men', price: 14.95, category: 'chilli men' },
    { id: 'item-51', name: 'yasai chilli men ', price: 11.5, category: 'chilli men'}
  ]
};
